version: "2"

services:
  talker:
    image: osrf/ros:humble-desktop
    volumes:
      - ./app1:/mon_code
    command: bash -c "source mon_code/install/setup.bash && ros2 run demo_nodes_cpp talker"

  listener:
    image: osrf/ros:humble-desktop
    volumes:
      - ./app2:/mon_code

    command: bash -c "source mon_code/install/setup.bash && ros2 run demo_nodes_cpp talker"

    depends_on:
      - talker
